image: ghcr.io/key4hep/key4hep-images/ubuntu22:latest

stages:
  - build
  - code-checks

build-job:
  stage: build
  needs: []
  tags:
    - cvmfs
  script:
    - source setup_env_nightly.sh
    - cmake -DCMAKE_CXX_STANDARD=20
            -DCMAKE_INSTALL_PREFIX=./install
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror "
            -GNinja
            -S . -B build
    - cmake --build build
    - cmake --build build --target install

  artifacts:
    paths:
      - install/
    expire_in: 1 day


pre-commit:
  stage: code-checks
  needs: []
  tags:
    - cvmfs
  script:
    - source setup_env_nightly.sh
    - cmake -DCMAKE_CXX_STANDARD=20
            -DCMAKE_INSTALL_PREFIX=./install
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror "
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
            -GNinja
            -S . -B build
    - ln -s build/compile_commands.json compile_commands.json
    - git config --global --add safe.directory $(pwd)
    - python -m venv /root/pre-commit-venv
    - source /root/pre-commit-venv/bin/activate
    - pip install pre-commit
    - pre-commit run --show-diff-on-failure --color=always --all-files
