image: ghcr.io/key4hep/key4hep-images/ubuntu22:latest

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - cvmfs

  script:
    - source setup_env_nightly.sh
    - cmake -DCMAKE_CXX_STANDARD=20
            -DCMAKE_INSTALL_PREFIX=./install
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror "
            -GNinja
            -S . -B build
    - cmake --build build
    - cmake --build build --target install

  artifacts:
    paths:
      - install/
    expire_in: 1 day

test-job:
  stage: test
  tags:
    - cvmfs
  script:
    - ls
    - pwd
    - source setup_env_nightly.sh

  artifacts:
    paths:
      - tests/
    expire_in: 1 week
  dependencies:
    - build-job

pre-commit:
  stage: build
  tags:
    - cvmfs
  script:
    - source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh
    - git config --global --add safe.directory $(pwd)
    - python -m venv /root/pre-commit-venv
    - source /root/pre-commit-venv/bin/activate
    - pip install pre-commit
    - pre-commit run --show-diff-on-failure --color=always --all-files
