image: ghcr.io/key4hep/key4hep-images/ubuntu22:latest

stages:
  - build

build-job:
  stage: build
  tags:
    - cvmfs

  script:
    - source setup_env_nightly.sh
    - cmake -DCMAKE_CXX_STANDARD=20
            -DCMAKE_INSTALL_PREFIX=./install
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror "
            -GNinja
            -S . -B build
    - cmake --build build
    - cmake --build build --target install

  artifacts:
    paths:
      - install/
    expire_in: 1 day
