image: ghcr.io/key4hep/key4hep-images/ubuntu22:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true" # This doesn't work with our current gitlab runner version (14.7.0) as it's introduced in 15.11. Have to resort to relative submodule path which breaks in case the project is forked.
  CI_DEBUG_TRACE: "true"

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == "PythonBindings"

stages:
  - build
  - test

build-job:
  stage: build
  tags:
    - cvmfs

  script:
#    - source /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-07-04/x86_64-ubuntu22.04-gcc11.3.0-opt/key4hep-stack/2023-07-03-okrjlh/setup.sh
    - source setup_env_nightly.sh
    - pwd
    - mkdir cmake-build
    - cd cmake-build
    - cmake ..
    - make -j install

  artifacts:
    paths:
      - install/
    expire_in: 1 day

test-job:
  stage: test
  script:
    - source setup_env_nightly.sh
    - cd tests
    - python test.py
  artifacts:
    paths:
      - tests/
    expire_in: 1 week
  dependencies:
    - build-job