#
#  test_onnx.mac
#  example script to run inference on a GAN w/ ONNX runtime

# --- the particle gun
/gps/pos/centre 0 0 0
/gps/particle  gamma
#/gps/particle  pi-
/gps/energy    20 GeV

# for SimpleCalo
#/gps/direction  -1 -0.25 2 #0.35 0.15 0.5  #0.25 0.23 0.5 #0.2 0.4 0.50  #-0.1 -1 2 #(-pi/2 -> -3pi/4) #0.1 -1 2 #(-pi/4 -> -pi/2) #0.23 0.23 0.5 
                #-1 0.1 2 #(3pi/4 -> pi)
                #0.2 0.5 0.65
                #1 -0.1 2
                #0.2 0.5 0.6
                #-1 -0.25 2
                #-1 -0.25 2 #(-3pi/4 -> -pi)
                #-0.1 -1 2 #(-pi/2 -> -3pi/4)
                #0.25 -1 2 #(-pi/4 -> -pi/2)
                #1 -0.1 2  #(0 -> -pi/4)
                #-1 0.1 2 (3pi/4 -> pi)
                #-0.2 0.9 2 (pi/2 -> 3pi/4)
                #0.1 1 2 (pi/4 -> pi/2)
                #1 0.1 2 # start from x axis (0 -> pi/4)
                #0.23 0.23 0.5  #0.15 0.10 0.5 #0.35 0.15 0.5 #0.25 0.25 0.5 #0. 0.5 0.5

                # Very corner of forward barrel 0.2 0.5 0.65  
                # 0.15 0.10 0.5 broken
                ##  0.05 0.10 0.5 works  

# for ILD barrel
/gps/ang/type iso
/gps/ang/mintheta 15. deg 
#/gps/ang/mintheta 145. deg #15. deg 
/gps/ang/maxtheta 165 deg #165. deg 


#/gps/ang/mintheta 45. deg 
#/gps/ang/maxtheta 135. deg 
#/gps/direction  0.1 -0.8 .1


/run/beamOn 10 #100

